import type { PRData, PRFile } from "../types.ts";
import { STYLES } from "../styles.ts";
import { renderDiffLines } from "./render-diff.ts";
import { escapeHtml } from "../escape.ts";

function renderFileCard(file: PRFile, index: number): string {
  const totalAdditions = file.additions;
  const totalDeletions = file.deletions;

  return `      <div class="file-card" id="file-${index}">
        <div class="file-header">
          <span class="file-status file-status-${file.status}">${file.status}</span>
          <span class="file-path">${escapeHtml(file.path)}</span>
          <span class="file-stats">
            <span class="stat-additions">+${totalAdditions}</span>
            <span class="stat-deletions">-${totalDeletions}</span>
          </span>
        </div>
        <div class="file-diff">
          <table class="diff-table">
            <tbody>
${renderDiffLines(file.diff)}
            </tbody>
          </table>
        </div>
        <div class="file-explanation">${escapeHtml(file.explanation)}</div>
      </div>`;
}

export function renderReport(pr: PRData, generatedAt: string): string {
  const totalAdditions = pr.files.reduce((sum, f) => sum + f.additions, 0);
  const totalDeletions = pr.files.reduce((sum, f) => sum + f.deletions, 0);
  const fileCards = pr.files.map((f, i) => renderFileCard(f, i)).join("\n\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(pr.title)}</title>
  <style>${STYLES}</style>
</head>
<body>
  <div class="main">
    <div class="pr-header">
      <h1 class="pr-title">${escapeHtml(pr.title)}</h1>
      <div class="pr-meta">
        <span class="pr-branch">${escapeHtml(pr.branch)}</span>
${pr.label ? `        <span class="pr-label">${escapeHtml(pr.label)}</span>\n` : ""}        <span class="pr-stats">
          <span class="stat-additions">+${totalAdditions}</span>
          <span class="stat-deletions">-${totalDeletions}</span>
        </span>
      </div>
      <div class="pr-description">${escapeHtml(pr.description)}</div>
    </div>

    <div class="files-summary">
      <strong>${pr.files.length}</strong> file${pr.files.length !== 1 ? "s" : ""} changed
      <span class="stat-additions">+${totalAdditions}</span>
      <span class="stat-deletions">-${totalDeletions}</span>
    </div>

${fileCards}

    <div class="report-footer">
      Generated by Quinn on ${escapeHtml(generatedAt)}
    </div>
  </div>
</body>
</html>`;
}
